usr/share/man/man7/*
usr/share/doc/prrte* /usr/share/doc/openmpi-doc/prrte
usr/share/doc/openmpi/html		usr/share/doc/openmpi-doc
usr/share/man/man1/mpisync.1
usr/share/man/man1/ompi-wrapper-compiler.1
usr/share/man/man1/oshmem-wrapper-compiler.1
usr/share/man/man1/prte.1
usr/share/man/man1/prte_info.1
usr/share/man/man1/prted.1
usr/share/man/man1/prterun.1
usr/share/man/man1/prun.1
usr/share/man/man1/pterm.openmpi.1
usr/share/man/man5/prte.5
